Menu cards (work with server by XMLHttpRequest))
Ekaterina-Kuzina/Food-project-JS-by-myself- pull request #4
Opened 2021-04-15 12:52 UTC by Ekaterina-Kuzina

2021-04-17 08:43 UTC, kicumkicum requested changes
Все очень хорошо 👍 Но нужно внести важные правки

2021-04-17 08:43 UTC, kicumkicum commented on .gitignore
> +# dependencies
idea нужно вернуть. Иначе будешь комитить директорию с настройками

2021-04-17 08:43 UTC, kicumkicum commented on js/script.js
> +                class MenuCard {
Класс нужно описывать в отдельном моделе - файле с таким же именем, как и класс - подключать его в шапке этого файла. Ну а дальше как у тебя и тебя и написано, создавать объекты с его помощью

2021-04-17 08:43 UTC, kicumkicum commented on js/script.js
> +
Столько пустых строк в файле быть не должно. Достаточно лишь одной

2021-04-17 08:43 UTC, kicumkicum requested changes
Все очень хорошо 👍 Но нужно внести важные правки

2021-04-25 19:54 UTC, kicumkicum requested changes
Отлично! Давай закончим разбираться со структурой, а потом перейдет уже к функциональности

2021-04-25 19:54 UTC, kicumkicum commented on .gitignore
> +# dependencies
done

2021-04-25 19:54 UTC, kicumkicum commented on README.md
> +Для старта сервера нужно выполнить команду `json-server server/db.json`.
Лучше бы эту команду поместить в npm-скрипт `server`, в `package.json`. Тогда тут не пришлось бы ничего менять

2021-04-25 19:54 UTC, kicumkicum commented on README.md
> -Для начала нужно установить зависимости командой `npm install`.
А что все еще важная информация

2021-04-25 19:54 UTC, kicumkicum commented on server/db.json
> +    },
А почему данные такие не консистентные? То бишь не однородные

2021-04-25 19:54 UTC, kicumkicum commented on js/script.js
> +                setTimeout(() => statusMessage.textContent = '', 2000);
Этот код достаточно сложный - обработчик. Давай сначала обсудим, почему он сложный

2021-04-25 19:54 UTC, kicumkicum commented on js/script.js
> +import {showModalByScroll} from './modals/showModalByScroll.js';
Импорты должны быть только в верху файла

2021-04-25 19:54 UTC, kicumkicum commented on js/script.js
> +//MODALS
Такие комментарии как бы намекают, что стоит разбить на модули

2021-04-25 19:54 UTC, kicumkicum commented on js/script.js
> +postData(forms);
Сложно читать работу, которую делает модуль. Потому что содержимое не структурировано. Обычно модули имеют примерно такую структуру:

```md
- Импорты
- Константы
- Объявление функций
- Объявление переменных
- Вызов функций
- Экспорты
```

2021-04-25 19:54 UTC, kicumkicum commented on js/modals/showModalByScroll.js
> +}
Нужно чтобы этих красных кружочков не было. Для этого нужно добавить перенос строки в конце файла

2021-04-27 09:01 UTC, Ekaterina-Kuzina commented on server/db.json
> +    },
Я пыталась отправлять данные с помощью FormData и в JSON формате . Когда отправляла с помощью FormData была такая проблема , что в данных отображается только id. Их нужно было удалить перед коммитом ? Просто я удаляла ,но при новой отправке данных опять они все возвращались

2021-04-27 09:15 UTC, Ekaterina-Kuzina commented on js/script.js
> +postData(forms);
т.е константы это переменные объявленные с помощью const , а после "Объявления функций" идут переменные let, var?

2021-04-27 10:34 UTC, Ekaterina-Kuzina commented on js/script.js
> +//MODALS
Если разбить TABS ,MODALS и тд на модули , то что будет делать основной общий файл script.js?

2021-04-27 20:10 UTC, kicumkicum commented on js/script.js
> +//MODALS
Собирать все воедино. Подключать необходимые рабочие модули. Вызывать функции. Запускать работу

2021-04-27 20:16 UTC, kicumkicum commented on js/script.js
> +postData(forms);
Не совсем. Для начала, всё есть переменные. Не важно каким словом они объявлены let или const. Просто некоторые можно переписывать, а некоторые нельзя. Константы это особые переменные, а не все те, которые объявлены с помощью const. Константы это переменные, которыми можно конфигурировать работу модуля. Например это может быть адрес сервера, на который ходит запрос. Очень удобно открыть модуль и увидеть, что можно конфигурировать и поменять это для тестирования например. То есть набор констант контекстно (смысловым образом) связаны с модулем в целом

2021-05-02 16:34 UTC, kicumkicum requested changes
Получилось все очень здорово. Поправь два коммента и можно мержить

2021-05-02 16:34 UTC, kicumkicum commented on js/tabs/tabs.js
> +makeTabs();
Кажется, что этот вызов лишний

2021-05-02 16:34 UTC, kicumkicum commented on js/menu-cards/MenuCard.js
> +        changeToRub() {
Можно обойтись и без этого метода, выполнив вычисление на строке 7

2021-05-02 17:51 UTC, merged